try:
    print("Start of try block")
    # prit("Error")
except:
    print("Exception caught")
